tasks/urls.py
from django.urls import path
from tasks import views

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('manager-dashboard/', views.manager_dashboard, name='manager-dashboard'),
    path('employee-dashboard/', views.employee_dashboard,
         name='employee-dashboard'),
    path('task-list', views.view_task, name='task-list'),
    path('create-task/', views.CreateTask.as_view(), name='create-task'),
    path('view-task/<int:id>/', views.TaskDetail.as_view(), name='view-task-detail'),
    path('update-task/<int:id>/', views.UpdateTask.as_view(), name='update-task'),
    path('delete-task/<int:id>/', views.delete_task, name='delete-task')
]

tasks/models.py
import cloudinary.uploader
from django.db import models
from django.conf import settings
from cloudinary.models import CloudinaryField


class Task(models.Model):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    STATUS_CHOICES = [
        (PENDING, 'Pending'),
        (IN_PROGRESS, 'In Progress'),
        (COMPLETED, 'Completed')
    ]
    project = models.ForeignKey(
        "Project",
        on_delete=models.CASCADE,
        default=1
    )
    assigned_to = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='tasks')
    title = models.CharField(max_length=250)
    description = models.TextField()
    due_date = models.DateField()
    status = models.CharField(
        max_length=15, choices=STATUS_CHOICES, default=PENDING)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # details

    def __str__(self):
        return self.title


class TaskDetail(models.Model):
    HIGH = 'H'
    MEDIUM = 'M'
    LOW = 'L'
    PRIORITY_OPTIONS = (
        (HIGH, 'High'),
        (MEDIUM, 'Medium'),
        (LOW, 'Low')
    )
    task = models.OneToOneField(
        Task,
        on_delete=models.CASCADE,
        related_name='details',
    )
    priority = models.CharField(
        max_length=1, choices=PRIORITY_OPTIONS, default=LOW)
    notes = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"Details form Task {self.task.title}"


class TaskAsset(models.Model):
    task_detail = models.ForeignKey(
        TaskDetail, on_delete=models.CASCADE, related_name='assets')
    image = CloudinaryField(blank=True, null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Asset for {self.task_detail.task.title}"


class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    start_date = models.DateField()

    def __str__(self):
        return self.name

tasks/forms.py
from django import forms
from tasks.models import Task, TaskDetail, TaskAsset
from core.mixins import StyledFormMixin


# Django Model Form


class TaskModelForm(StyledFormMixin, forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'due_date', 'assigned_to', 'project']
        widgets = {
            'due_date': forms.SelectDateWidget,
            'assigned_to': forms.CheckboxSelectMultiple
        }


class TaskDetailModelForm(StyledFormMixin, forms.ModelForm):
    class Meta:
        model = TaskDetail
        fields = ['priority', 'notes']


class TaskAssetForm(StyledFormMixin, forms.ModelForm):
    class Meta:
        model = TaskAsset
        fields = ['image']

tasks/views.py
from django.shortcuts import render, redirect
from django.db.models import Q, Count, Prefetch
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import user_passes_test, login_required, permission_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views import View
from django.views.generic import UpdateView, DetailView
from django.views.generic.base import ContextMixin
from tasks.forms import TaskModelForm, TaskDetailModelForm, TaskAssetForm
from tasks.models import Task, TaskAsset
from users.views import is_admin

User = get_user_model()


def is_manager(user):
    return user.groups.filter(name='Manager').exists()


def is_employee(user):
    return user.groups.filter(name='Employee').exists()


@login_required
def dashboard(request):
    if is_manager(request.user):
        return redirect('manager-dashboard')
    elif is_employee(request.user):
        return redirect('employee-dashboard')
    elif is_admin(request.user):
        return redirect('admin-dashboard')

    return redirect('no-permission')


@login_required
@user_passes_test(is_manager, login_url='no-permission')
def manager_dashboard(request):
    counts = Task.objects.aggregate(
        total=Count('id'),
        completed=Count('id', filter=Q(status='COMPLETED')),
        in_progress=Count('id', filter=Q(status='IN_PROGRESS')),
        pending=Count('id', filter=Q(status='PENDING')),
    )

    # Retriving task data
    tasks = Task.objects.select_related(
        'details').prefetch_related('assigned_to').all()

    context = {
        "tasks": tasks,
        "counts": counts
    }
    return render(request, "dashboard/manager_dashboard.html", context)


@login_required
@user_passes_test(is_employee, login_url='no-permission')
def employee_dashboard(request):
    return render(request, "dashboard/employee-dashboard.html")


class CreateTask(ContextMixin, LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = 'tasks.add_task'
    login_url = 'sign-in'
    template_name = 'task_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task_form'] = kwargs.get('task_form', TaskModelForm())
        context['task_detail_form'] = kwargs.get(
            'task_detail_form', TaskDetailModelForm())
        context['task_asset_form'] = TaskAssetForm()
        if self.request.user.groups.filter(name="Admin").exists():
            context["base_template"] = "admin/admin-dashboard.html"
        else:
            context["base_template"] = "dashboard/dashboard.html"
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        task_form = TaskModelForm(request.POST)
        task_detail_form = TaskDetailModelForm(request.POST, request.FILES)
        task_asset_form = TaskAssetForm(request.POST, request.FILES)

        if task_form.is_valid() and task_detail_form.is_valid() and task_asset_form.is_valid():

            """ For Model Form Data """
            task = task_form.save()
            task_detail = task_detail_form.save(commit=False)
            task_detail.task = task
            task_detail.save()

            # Handle Task Assets
            for image in request.FILES.getlist('image'):
                task_asset = TaskAsset(task_detail=task_detail, image=image)
                task_asset.save()

            messages.success(request, "Task Created Successfully")
            context = self.get_context_data(
                task_form=task_form, task_detail_form=task_detail_form)
            return render(request, self.template_name, context)

        # Handle form errors (Important!)
        context = self.get_context_data(
            # Pass forms back to the template
            task_form=task_form, task_detail_form=task_detail_form, task_asset_form=task_asset_form)
        messages.error(request, "There were errors in the form.")
        return render(request, self.template_name, context)


class UpdateTask(UpdateView):
    model = Task
    form_class = TaskModelForm
    template_name = 'task_form.html'
    context_object_name = 'task'
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task_form'] = self.get_form()
        if hasattr(self.object, 'details') and self.object.details:
            context['task_detail_form'] = TaskDetailModelForm(
                instance=self.object.details)
        else:
            context['task_detail_form'] = TaskDetailModelForm()
        if self.request.user.groups.filter(name="Admin").exists():
            context["base_template"] = "admin/admin-dashboard.html"
        else:
            context["base_template"] = "dashboard/dashboard.html"
        context['task_asset_form'] = TaskAssetForm()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        task_form = TaskModelForm(request.POST, instance=self.object)
        task_detail_form = TaskDetailModelForm(
            request.POST, request.FILES, instance=getattr(self.object, 'details', None))
        task_asset_form = TaskAssetForm(
            request.POST, request.FILES)  # Initialize asset form

        if task_form.is_valid() and task_detail_form.is_valid() and task_asset_form.is_valid():
            task = task_form.save()
            task_detail = task_detail_form.save(commit=False)
            task_detail.task = task
            task_detail.save()

            # Handle new asset uploads
            for image in request.FILES.getlist('image'):
                task_asset = TaskAsset(task_detail=task_detail, image=image)
                task_asset.save()

            # Handle existing asset deletions
            assets_to_delete = []
            for asset in self.object.details.assets.all():  # Iterate through all assets
                asset_id_key = f"asset_id_{asset.id}"
                delete_key = f"delete_asset_{asset.id}"

                if asset_id_key in request.POST:  # check if the asset_id is in the post data
                    # if the delete checkbox is on then add it to the list to delete
                    if delete_key in request.POST and request.POST[delete_key] == "on":
                        assets_to_delete.append(asset.id)

            print(assets_to_delete)  # Now it will work correctly!
            for asset_id in assets_to_delete:
                asset = TaskAsset.objects.get(pk=asset_id)
                asset.delete()

            messages.success(request, "Task Updated Successfully")
            return redirect('update-task', self.object.id)

        # Handle form errors (Important!)
        context = self.get_context_data(
            task_form=task_form, task_detail_form=task_detail_form, task_asset_form=task_asset_form)
        messages.error(request, "There were errors in the form.")
        return render(request, self.template_name, context)


def delete_task(request, id):
    if request.method == 'POST':
        task = Task.objects.get(id=id)
        task.delete()
        messages.success(request, 'Task Deleted Successfully')
        return redirect('task-list')
    else:
        messages.error(request, 'Something went wrong')
        return redirect('task-list')


@permission_required('tasks.view_task', login_url='no-permission')
def view_task(request):
    type = request.GET.get('type', 'all')

    base_query = Task.objects.select_related(
        'details').prefetch_related('assigned_to', 'details__assets').select_related('project')

    if type == 'completed':
        tasks = base_query.filter(status='COMPLETED')
    elif type == 'in-progress':
        tasks = base_query.filter(status='IN_PROGRESS')
    elif type == 'pending':
        tasks = base_query.filter(status='PENDING')
    elif type == 'all':
        tasks = base_query.all()

    context = {
        "tasks": tasks
    }

    if request.user.groups.filter(name="Admin").exists():
        context["base_template"] = "admin/admin-dashboard.html"
    else:
        context["base_template"] = "dashboard/dashboard.html"

    return render(request, "task-list.html", context)


@method_decorator(login_required, name='dispatch')
@method_decorator(permission_required("tasks.view_task", login_url='no-permission'), name='dispatch')
class TaskDetail(DetailView):
    model = Task
    template_name = 'task_details.html'
    context_object_name = 'task'
    pk_url_kwarg = 'id'

    def get_queryset(self):
        queryset = super().get_queryset()

        return queryset.select_related('details').prefetch_related(
            'details__assets',
            Prefetch(
                'assigned_to__groups',
                queryset=Group.objects.all(),  # Ensures a single optimized query for groups
                to_attr='prefetched_groups'  # Stores results in a custom attribute
            )
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['status_choices'] = Task.STATUS_CHOICES
        is_admin = self.request.user.groups.filter(name="Admin").exists()
        context["base_template"] = "admin/admin-dashboard.html" if is_admin else "dashboard/dashboard.html"
        return context

    def post(self, request, *args, **kwargs):
        task = self.get_object()
        selected_status = request.POST.get('task_status')
        task.status = selected_status
        task.save()
        return redirect('view-task-detail', task.id)

tasks/templates/dashboard/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/output.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}" >
</head>
<body class="bg-gray-100 font-sans">
    <div class="flex flex-col md:flex-row min-h-screen">
        {% comment %} Sidebar {% endcomment %}
        <aside class="w-full md:w-64 bg-white shadow-md">
            <div class="p-4">
                <div class="flex items-center space-x-2 mb-6">
                    <div class="w-8 h-8 bg-blue-500 rounded-full flex items-center justify-center">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-white" viewBox="0 0 20 20" fill="currentColor">
                            <path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z" />
                            <path fill-rule="evenodd" d="M4 5a2 2 0 012-2 3 3 0 003 3h2a3 3 0 003-3 2 2 0 012 2v11a2 2 0 01-2 2H6a2 2 0 01-2-2V5zm3 4a1 1 0 000 2h.01a1 1 0 100-2H7zm3 0a1 1 0 000 2h3a1 1 0 100-2h-3zm-3 4a1 1 0 100 2h.01a1 1 0 100-2H7zm3 0a1 1 0 100 2h3a1 1 0 100-2h-3z" clip-rule="evenodd" />
                        </svg>
                    </div>
                    <a href="{% url 'home' %}" class="text-xl font-semibold">
                        Taskify
                    </a>
                </div>
                <nav class="space-y-2">
                    <a href="{% url 'manager-dashboard' %}" class="block py-2 px-4 rounded-md  {% if request.resolver_match.url_name == 'manager-dashboard' %} bg-blue-500 text-white {% else %} text-gray-600 hover:bg-gray-100{% endif %}">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline-block mr-2" viewBox="0 0 20 20" fill="currentColor">
                            <path d="M2 4a1 1 0 011-1h2a1 1 0 011 1v12a1 1 0 01-1 1H3a1 1 0 01-1-1V4zM8 4a1 1 0 011-1h2a1 1 0 011 1v12a1 1 0 01-1 1H9a1 1 0 01-1-1V4zM15 3a1 1 0 00-1 1v12a1 1 0 001 1h2a1 1 0 001-1V4a1 1 0 00-1-1h-2z" />
                        </svg>
                        Dashboard
                    </a>
                    <a href='{% url "task-list" %}' class="block py-2 px-4 rounded-md {% if request.get_full_path == '/tasks/task-list' %} bg-blue-500 text-white {% else %} text-gray-600 hover:bg-gray-100{% endif %}">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline-block mr-2" viewBox="0 0 24 24" fill="currentColor">
                            <path d="M8 2a1 1 0 00-1 1v1H5a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2V6a2 2 0 00-2-2h-2V3a1 1 0 00-1-1H8zm1 2h6v1H9V4zm-2 3h10v12H7V7zm2 2a1 1 0 100 2h6a1 1 0 100-2H9z"/>
                        </svg>
                        
                        All Task
                    </a>
                    <a href="{% url 'task-list' %}?type=pending" class="block py-2 px-4 rounded-md {% if request.get_full_path == '/tasks/task-list?type=pending' %} bg-blue-500 text-white {% else %} text-gray-600 hover:bg-gray-100{% endif %}">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline-block mr-2" viewBox="0 0 24 24" fill="currentColor">
                            <path d="M6 2a1 1 0 000 2h12a1 1 0 100-2H6zm6 8a5.98 5.98 0 01-4.24-1.76A1 1 0 018 7h8a1 1 0 01.24 1.24A5.98 5.98 0 0112 10zm0 2c1.6 0 3.07.62 4.24 1.76A1 1 0 0116 15H8a1 1 0 01-.24-1.24A5.98 5.98 0 0112 12zm6 10a1 1 0 000-2H6a1 1 0 100 2h12z"/>
                        </svg>                        
                        Pending
                    </a>
                    <a href="{% url 'task-list' %}?type=completed" class="block py-2 px-4 rounded-md {% if request.get_full_path == '/tasks/task-list?type=completed' %} bg-blue-500 text-white {% else %} text-gray-600 hover:bg-gray-100{% endif %}">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline-block mr-2" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                        </svg>
                        Completed
                    </a>
                    <a href="{% url 'task-list' %}?type=in-progress" class="block py-2 px-4 rounded-md {% if request.get_full_path == '/tasks/task-list?type=in-progress' %} bg-blue-500 text-white {% else %} text-gray-600 hover:bg-gray-100{% endif %}">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline-block mr-2" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.415-1.415L11 9.586V6z" clip-rule="evenodd" />
                        </svg>
                        In Progress
                    </a>
                    <a href='{% url "create-task" %}' class="block py-2 px-4 rounded-md {% if request.resolver_match.url_name == 'create-task' %} bg-blue-500 text-white {% else %} text-gray-600 hover:bg-gray-100{% endif %}">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline-block mr-2" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-11a1 1 0 10-2 0v2H7a1 1 0 100 2h2v2a1 1 0 102 0v-2h2a1 1 0 100-2h-2V7z" clip-rule="evenodd" />
                        </svg>
                        Create Task
                    </a>
                    <a href="{% url 'profile' %}" class="block py-2 px-4 rounded-md {% if request.resolver_match.url_name == 'other' %} bg-blue-500 text-white {% else %} text-gray-600 hover:bg-gray-100{% endif %}">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline-block mr-2" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd" />
                        </svg>
                        Profile
                    </a>
                    <form action="{% url 'logout' %}" method='post' class="block py-2 px-4 rounded-md {% if request.resolver_match.url_name == 'other' %} bg-blue-500 text-white {% else %} text-gray-600 hover:bg-gray-100{% endif %}">
                        {% csrf_token %}
                        <button type='submit'>
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline-block mr-2" viewBox="0 0 20 20" fill="currentColor">
                                <path fill-rule="evenodd" d="M3 3a1 1 0 00-1 1v12a1 1 0 001 1h12a1 1 0 001-1V3a1 1 0 00-1-1H3zm10.293 9.293a1 1 0 001.414 1.414l3-3a1 1 0 000-1.414l-3-3a1 1 0 10-1.414 1.414L14.586 9H7a1 1 0 100 2h7.586l-1.293 1.293z" clip-rule="evenodd" />
                            </svg>
                            Logout
                        </button>
                    </form>
                </nav>
            </div>
        </aside>

        {% comment %} Main Content {% endcomment %}
        <main class="flex-1 p-4 md:p-8">
            <div class="flex justify-between items-center mb-8">
                <h1 class="text-2xl font-semibold">Dashboard {% block dash-title %}{% endblock dash-title %}</h1>
                <div class="flex items-center space-x-4">
                    <button class="p-2 rounded-full bg-gray-200 hover:bg-gray-300">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
                        </svg>
                    </button>
                    <div class="w-9 h-9 bg-blue-500 rounded-full flex items-center justify-center text-white font-semibold">
                        <img class="w-9 h-9 rounded-full object-cover" src="{{ request.user.profile_image.url }}" alt="User avatar">
                    </div>
                </div>
            </div>
            {% if messages %}
                <div class='mx-auto w-2/3 my-5'>
                    {% for message in messages %}
                        <div class="px-2 py-3 border rounded-md text-center text-white {% if message.tags == 'success' %}bg-green-500 {% else %} bg-red-500 {% endif %}">{{message}}</div>
                    {% endfor %}
                </div>
            {% endif %}
            {% block content %}{% endblock content %}
        </main>
    </div>
</body>
</html>

tasks/templates/dashboard/manager_dashboard.html
{% extends "dashboard/dashboard.html" %}
{% load color_class_filters %}
{% block title %}Manager Dashboard{% endblock title %}

{% block content %}

{% include "dashboard/stats-grid.html" %}

<div class="bg-white rounded-lg shadow overflow-x-auto">
    <table class="w-full">
        <thead>
            <tr class="bg-gray-100">
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Task Title
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Priority
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Team
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Created At
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Status
                </th>
            </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
            {% for task in tasks %}
                <tr>
                    <td class="px-6 py-4 whitespace-nowrap">
                        <div class="flex items-center">
                            <div class="flex-shrink-0 h-4 w-4 rounded-full bg-green-500"></div>
                            <div class="ml-4">
                                <a href="{% url 'view-task-detail' task.id %}" class="hover:underline hover:text-blue-800">{{ task.title }}</a>
                            </div>
                        </div>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap">
                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full {{ task.details.priority|priority_color_class }}">
                            {{ task.details.get_priority_display }}
                        </span>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap">
                        <div class="flex -space-x-2 overflow-hidden">
                            {% for emp in task.assigned_to.all %}
                                <div class="h-6 w-6 rounded-full 
                                            {% cycle 'bg-blue-500' 'bg-yellow-500' 'bg-indigo-500' 'bg-red-500' %}
                                            text-white text-xs flex items-center justify-center">
                                    {{ emp.first_name|slice:":1" }}
                                </div>
                            {% endfor %}
                        </div>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {{ task.created_at|timesince }}
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap">
                        <span class="px-2 text-xs font-semibold rounded-full {{ task.status|status_color_class }}">{{task.get_status_display}}</span>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

tasks/templates/dashboard/stats-grid.html
<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
    <div class="bg-white rounded-lg shadow p-6">
        <h2 class="text-xl font-semibold mb-2">TOTAL TASK</h2>
        <p class="text-3xl font-bold">{{counts.total}}</p>
        <p class="text-gray-500">111 last month</p>
        <div class="mt-4 w-10 h-10 bg-blue-100 rounded-full flex items-center justify-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-blue-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
            </svg>
        </div>
    </div>
    <div class="bg-white rounded-lg shadow p-6">
        <h2 class="text-xl font-semibold mb-2">COMPLETED TASK</h2>
        <p class="text-3xl font-bold">{{counts.completed}}</p>
        <p class="text-gray-500">111 last month</p>
        <div class="mt-4 w-10 h-10 bg-green-100 rounded-full flex items-center justify-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
            </svg>
        </div>
    </div>
    <div class="bg-white rounded-lg shadow p-6">
        <h2 class="text-xl font-semibold mb-2">TASK IN PROGRESS</h2>
        <p class="text-3xl font-bold">{{counts.completed}}</p>
        <p class="text-gray-500">111 last month</p>
        <div class="mt-4 w-10 h-10 bg-yellow-100 rounded-full flex items-center justify-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-yellow-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
        </div>
    </div>
    <div class="bg-white rounded-lg shadow p-6">
        <h2 class="text-xl font-semibold mb-2">TODOS</h2>
        <p class="text-3xl font-bold">{{counts.pending}}</p>
        <p class="text-gray-500">111 last month</p>
        <div class="mt-4 w-10 h-10 bg-purple-100 rounded-full flex items-center justify-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-purple-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" />
            </svg>
        </div>
    </div>
</div>

tasks/templates/dashboard/user-dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>User Dashboard</h1>
</body>
</html>